exp_name: 'Experiments speech TALSP2025'

exp_common:
  speech_num_mics:
    varying_factors: [ 'num_mics_max' ]
    num_mics_max: [ 2, 4, 6 ]  # real is [2,4,6,8]. This is for testing

  speech_nstft:
    varying_factors: [ 'nstft' ]
    nstft: [ 512, 1024, 2048 ]

  speech_time_seconds:
    varying_factors: [ 'duration_output_sec' ]
    duration_output_sec: [ 0.25, 0.5, 1. , 2 ]
    duration_output_sec_display: [ 0.3, 0.6, 1., 2 ]

  speech_snr:
    varying_factors: [ 'noises_info', 0, 'snr' ]
    noises_info:
      [
        { 'snr': [ -10, 0, 10, 20, 30, 40 ],
          'names': ['long_vowel'],  # [ 'esc-50-selected' ] is the correct one! 'long_vowel' is for testing
          'same_volume_all_mics': False,
          'isDirectional': True },
        { 'snr': [ 40 ], 'names': [ 'white' ], 'same_volume_all_mics': True, 'isDirectional': False },
      ]

  speech_noise_position:
    varying_factors: ['rir_settings', 'noise_angle']
    rir_settings:
      noise_angle: [ 0, 15, 30, 45, 60, 75, 90]
      rtf_type: 'real'
      rir_corpus: 'pyroom' #'hadad' is the correct one! pyroom is for testing
      room_size: 'large'
      num_nonzero_samples_rir_target: 6100
      num_nonzero_samples_rir_noise: 6100
      target_angle: 45
      noise_distance: 1
      target_distance: 2

  speech_plot_correlation:
    varying_factors: [ 'duration_output_frames' ]
    duration_output_frames: [ 5, 10, 15 ]
    num_repeated_experiments: 10
    num_mics_max:  2
    plot_correlation_histogram: True
    freq_range_hz: [80, 1500]
    noverlap_percentage: [0.5]
    nstft: [1024]
#    desired: ['male', 'female']
    desired: ['white']
    noises_info:
      [
        { 'snr': [ 40 ], 'names': [ 'white' ], 'same_volume_all_mics': True, 'isDirectional': False },
      ]

  speech_noverlap:
    varying_factors: [ 'noverlap_percentage' ]
    noverlap_percentage: [ 0.5, 0.75, 0.96875 ]

algo_names: ['CW-SV', 'CW-SV-orig-phase', 'CW']
num_mics_max:  4
nstft: [1024]
noverlap_percentage: [0.75]
avg_time_frames: True
num_repeated_experiments: 1
duration_output_sec: 1

desired: ['demo_target'] # real is ['male', 'female']. This is for testing

noises_info:
    [
      { 'snr': [ 0 ],
        'names': ['long_vowel'],  # [ 'esc-50-selected' ] is the correct one! 'long_vowel' is for testing
        'same_volume_all_mics': False, 'isDirectional': True },
      { 'snr': [ 40 ], 'names': [ 'white' ], 'same_volume_all_mics': True, 'isDirectional': False },
    ]

max_relative_difference_loud_bins: 35

rir_settings:
  rtf_type: 'real'
  rir_corpus: 'pyroom' #'hadad' is the correct one! pyroom is for testing
  room_size: 'large'
  num_nonzero_samples_rir_target: 6100
  num_nonzero_samples_rir_noise: 6100
  noise_angle: 60
  target_angle: 45
  noise_distance: 1
  target_distance: 1

needs_warmup_run: False
gen_signals_freq_domain: False
use_true_noise_covariance: False
perc_active_target_freq: 1.0
single_frame_phase_range_end: 0.5

add_identity_noise_noisy: True

rtf_metrics: ['Hermitian angle', 'RMSE dB']

beamforming_algorithm: 'mvdr'
beamforming_metrics: ['fwSNRseg', 'STOI', 'llr']

processed_freq_range_hz: [80, 2000]
