#!/bin/bash

exp_constant=$1
echo "Running experiments with exp_constant = $exp_constant. Higher exp_constant means more Montecarlo trials. Typical values are 1, 1e6, 1e9 etc."

if [ $# -ge 2 ]; then
    if [ "$2" = "equal" ]; then
      echo "Running with equal variances."
      python -m scripts.run_experiments  \
      --exp_name time_frames --repeated_experiments_constant "$exp_constant" --target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name noise_correlation --repeated_experiments_constant "$exp_constant" --target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name target_correlation --repeated_experiments_constant "$exp_constant" --target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name snr --repeated_experiments_constant "$exp_constant" --target_noise_equal_variances
      echo "Running with equal variances."
  elif [ "$2" = "unequal" ]; then
      echo "Running with UNequal variances."
      python -m scripts.run_experiments  \
      --exp_name time_frames --repeated_experiments_constant "$exp_constant" --no-target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name noise_correlation --repeated_experiments_constant "$exp_constant" --no-target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name target_correlation --repeated_experiments_constant "$exp_constant" --no-target_noise_equal_variances &
      python -m scripts.run_experiments  \
      --exp_name snr --repeated_experiments_constant "$exp_constant" --no-target_noise_equal_variances
      echo "Running with UNequal variances."
    else
        echo "Invalid second argument: $2"
        echo "Valid arguments are 'equal' or 'unequal'."
    fi
else
    echo "No second argument provided."
    echo "Valid second arguments are 'equal' or 'unequal'."
    echo "Valid first arguments are 1, 1e6 etc. (the constant for the number of repeated experiments)."
fi
